#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BPAUTO_AVERAGE 1
#define CPTCFG_BPAUTO_NEW_LEDS 1
#define CPTCFG_BPAUTO_LEDS_CLASS 1
#define CPTCFG_BPAUTO_LEDS_TRIGGERS 1
#define CPTCFG_BPAUTO_CRYPTO_CCM 1
#define CPTCFG_BPAUTO_RHASHTABLE 1
#define CPTCFG_CFG80211_MODULE 1
#define CPTCFG_MAC80211_MODULE 1
#define CPTCFG_MAC80211_HAS_RC 1
#define CPTCFG_MAC80211_RC_MINSTREL 1
#define CPTCFG_MAC80211_RC_MINSTREL_HT 1
#define CPTCFG_MAC80211_RC_DEFAULT_MINSTREL 1
#define CPTCFG_MAC80211_RC_DEFAULT "minstrel_ht"
#define CPTCFG_MAC80211_MESH 1
#define CPTCFG_MAC80211_LEDS 1
#define CPTCFG_MAC80211_DEBUGFS 1
#define CPTCFG_MAC80211_DEBUG_MENU 1
#define CPTCFG_MAC80211_VERBOSE_DEBUG 1
#define CPTCFG_MAC80211_MLME_DEBUG 1
#define CPTCFG_MAC80211_STA_DEBUG 1
#define CPTCFG_MAC80211_HT_DEBUG 1
#define CPTCFG_MAC80211_PS_DEBUG 1
#define CPTCFG_WLAN 1
#define CPTCFG_ATH_COMMON_MODULE 1
#define CPTCFG_ATH_CARDS_MODULE 1
#define CPTCFG_ATH_DEBUG 1
#define CPTCFG_ATH9K_HW_MODULE 1
#define CPTCFG_ATH9K_COMMON_MODULE 1
#define CPTCFG_ATH9K_BTCOEX_SUPPORT 1
#define CPTCFG_ATH9K_MODULE 1
#define CPTCFG_ATH9K_PCI 1
#define CPTCFG_ATH9K_DEBUGFS 1
#define CPTCFG_ATH9K_STATION_STATISTICS 1
#define CPTCFG_ATH9K_RFKILL 1
#define CPTCFG_ATH9K_PCOEM 1
#define CPTCFG_ATH9K_HTC_MODULE 1
#define CPTCFG_ATH9K_HTC_DEBUGFS 1
#define CPTCFG_RTL_CARDS_MODULE 1
#define CPTCFG_RTL8192CU_MODULE 1
#define CPTCFG_RTLWIFI_MODULE 1
#define CPTCFG_RTLWIFI_USB_MODULE 1
#define CPTCFG_RTLWIFI_DEBUG 1
#define CPTCFG_RTL8192C_COMMON_MODULE 1
#define CPTCFG_ETHERNET 1
#define CPTCFG_NET_VENDOR_ATHEROS 1
#define CPTCFG_NET_VENDOR_BROADCOM 1
#define CPTCFG_NET_VENDOR_INTEL 1
#define CPTCFG_USB_NET_DRIVERS_MODULE 1
#define CPTCFG_SSB_POSSIBLE 1
#define CPTCFG_BCMA_POSSIBLE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
